export { default as DataPaging } from "./controls/DataPaging.vue";
export { default as DataTable } from "./controls/DataTable.vue";
export { default as InputDate } from "./controls/InputDate.vue";
export { default as InputMask } from "./controls/InputMask.vue";
export { default as InputMoney } from "./controls/InputMoney.vue";
export { default as InputNumber } from "./controls/InputNumber.vue";
export { default as InputTime } from "./controls/InputTime.vue";
export { default as LoadingPage } from "./controls/LoadingPage.vue";
export { default as PageHeader } from "./controls/PageHeader.vue";
